# Default values for spring-boot-API.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: stable

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ports:
  - name: http
    containerPort: 8080
    path: /api
  - name: logs
    containerPort: 8081
    path: /logs
  - name: soap
    containerPort: 8082
    path: /soap

env: []
