apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prd-project
  namespace: argocd
spec:
  description: Prd environment apps
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

