apiVersion: v1
kind: ConfigMap
metadata:
  name: config-json
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "appName": "Spring-Boot-API",
      "env": "{{ .Values.env }}"
    }

