apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-api-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          {{- range .Values.ports }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: spring-boot-api
                port:
                  number: {{ .containerPort }}
          {{- end }}

