apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-api-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ randAlphaNum 10 | b64enc }}
  password: {{ randAlphaNum 20 | b64enc }}
