apiVersion: v1
kind: Service
metadata:
  name: spring-boot-api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: spring-boot-api
  ports:
    {{- range .Values.ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      name: {{ .name }}
    {{- end }}

